### ISSUE TITLE
Add go-lint to workflow.yaml

### ISSUE THREAD

**Issue by vGsteiger** [ubc-cirrus-lab/caribou#289]
Make the Go code golint compatible, then add the following to workflow.yaml:

```yaml
go-lint:
  runs-on: ubuntu-latest
  if: ${{ !github.event.pull_request.draft }}
  timeout-minutes: 5
  steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: ./.github/actions/go
    - name: Run Go linters
      run: |
        cd caribou-go
        go get -u golang.org/x/lint/golint
        golint ./...
        go vet ./...
```
