### ISSUE TITLE
Move regions_and_providers to top level and move providers

### ISSUE THREAD

**Issue by Danidite** [ubc-cirrus-lab/caribou#30]
Move regions_and_providers to top level and move providers into regions_and_providers in the config.yml file and properly propagate this change. 

```yaml
regions_and_providers: # Either the user specify only allowed regions (which will override everything else)
  only_regions: null # Only check other conditions if this is None, else will restrict to ONLY those regions
  forbidden_regions: null
  providers:
    - name: "aws"
      config:
        timeout: 60
        memory: 128
```
